# Generated by Django 3.2 on 2024-02-03 14:13

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимый никнейм. Допустимы только буквы, цифры и @/./+/-/_ .', regex='^[\\w.@+-]+\\Z'), users.models.validate_username_uniqueness]),
        ),
    ]
