# Generated by Django 3.2 on 2024-02-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
